# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-22 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170722_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postcategory',
            field=models.CharField(choices=[('SPOT', 'SPOT'), ('ACCOMODATION', 'ACCOMODATION'), ('RESTAURANT', 'RESTAURANT')], default='SPOT', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
