# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 08:37
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='https://www.youtube.com/watch?v=STE2uqh-xqg'),
        ),
    ]
