# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.TextField(default='정확한 주소를 입력해주세요.', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.TextField(default='정확한 명칭을 입력해주세요.', max_length=50),
        ),
    ]
