# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170810_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.TextField(default='정확한 주소를 입력해주세요.', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.TextField(default='정확한 명칭을 입력해주세요.', max_length=20),
        ),
    ]
