# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 07:10
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170810_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(default='base.jpeg', upload_to='blog/post'),
        ),
    ]
