# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170813_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postcategory',
            field=models.CharField(choices=[('SPOT', 'SPOT'), ('ACCOMODATION', 'ACCOMODATION'), ('RESTAURANT', 'RESTAURANT'), ('RECREATION', 'RECREATION')], default='SPOT', max_length=20),
        ),
    ]
