# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-23 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='author',
        ),
    ]
