# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-23 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20170823_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=40),
        ),
    ]
