# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20170824_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.TextField(default='정확한 명칭을 입력해주세요.', max_length=40),
        ),
    ]
