# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-03 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20170902_1245'),
    ]
    
    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag_name', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag_set',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.CharField(blank=True, max_length=140, unique=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtag_set',
            field=models.ManyToManyField(blank=True, to='blog.Hashtag'),
        ),
    ]
