# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-03 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_post_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hash',
        ),
    ]
