# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_remove_post_hash'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Vrtag',
        ),
    ]
