# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20170904_1254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vrtag',
            new_name='Tag',
        ),
    ]
