# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20170904_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.TextField(default=True, verbose_name='HASHTAG'),
        ),
    ]
