# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20170905_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.TextField(blank=True, verbose_name='HASHTAG'),
        ),
    ]
