# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20170905_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contents',
            field=models.TextField(default='좋은 장소를 다른 사람들에게 소개해주세요!', max_length=500),
        ),
    ]
