# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_post_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.TextField(verbose_name='HASHTAG'),
        ),
    ]
