# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_auto_20170907_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postcategory',
            field=models.CharField(choices=[('SPOT', 'SPOT'), ('ACCOMODATION', 'ACCOMODATION'), ('RESTAURANT', 'RESTAURANT'), ('ACTIVITY', 'ACTIVITY')], default='SPOT', max_length=20),
        ),
    ]
